
language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t anushka/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anushka/docker-react npm run test